### PR TITLE
Create all_files_mehmet_osman_akgun.py

### PR DESCRIPTION
**Pull request by einsteinpikachu**
## Checklist
- [+] I have read the [CONTRIBUTING]
- [+] I have performed a self-review of my own code
- [+] I have run the code locally and it works as expected
- [+] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by einsteinpikachu** [comment]
changed folder position hw to week02

**Review by canbula — CHANGES_REQUESTED** [review]
Remove `print` usage from your files.

**Comment by einsteinpikachu** [comment]
print usage removed

**Review by canbula — APPROVED** [review]
💯

**Pull request merged**
