### PR TITLE
Create decorators_bilal_ayakdas.py

### PR DESCRIPTION
**Pull request by Bilal-AYAKDAS**
## Checklist
- [ ] I have read the [CONTRIBUTING]
- [ ] I have performed a self-review of my own code
- [ ] I have run the code locally and it works as expected
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by canbula — CHANGES_REQUESTED** [review]
Calling the function two times is not the correct thing to do.

**Review by Bilal-AYAKDAS — COMMENTED** [review]
The function result is assigned to the result variable.

**Review by canbula — CHANGES_REQUESTED** [review]
`sys` is not the correct module to use here. Try another one.

**Review by canbula — APPROVED** [review]
👍

**Pull request merged**
