### PR TITLE
Create threaded_furkan_bulut.py

### PR DESCRIPTION
**Pull request by Furk4nBulut**
## Checklist
- [X] I have read the [CONTRIBUTING]
- [X] I have performed a self-review of my own code
- [X] I have run the code locally and it works as expected
- [X] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by canbula — CHANGES_REQUESTED** [review]
Solve this with 2 functions, 3 wrapped functions are redundant.

**Review by Furk4nBulut — COMMENTED** [review]
## Describe your changes

## Checklist
- [X] I have read the [CONTRIBUTING]
- [X] I have performed a self-review of my own code
- [X] I have run the code locally and it works as expected
- [X] I have commented my code, particularly in hard-to-understand areas

**Review by canbula — CHANGES_REQUESTED** [review]
Reduce the number of inner functions.

**Review by Furk4nBulut — COMMENTED** [review]
## Describe your changes

## Checklist
- [X] I have read the [CONTRIBUTING]
- [X] I have performed a self-review of my own code
- [X] I have run the code locally and it works as expected
- [X] I have commented my code, particularly in hard-to-understand areas

**Review by Furk4nBulut — COMMENTED** [review]
## Describe your changes
Refactored the code to a class-based implementation. 
## Checklist
- [X] I have read the [CONTRIBUTING]
- [X] I have performed a self-review of my own code
- [X] I have run the code locally and it works as expected
- [X] I have commented my code, particularly in hard-to-understand areas

**Review by canbula — APPROVED** [review]
👍

**Pull request merged**
