### PR TITLE
Create types_sinem_gencer.py

### PR DESCRIPTION
**Pull request by myr2001**
## Checklist
- [X] I have read the [CONTRIBUTING]
- [X] I have performed a self-review of my own code
- [ ] I have run the code locally and it works as expected
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by canbula — CHANGES_REQUESTED** [review]
Don't use `hw` folder. You should create your file in `Week02` folder.

**Review by canbula — CHANGES_REQUESTED** [review]
Move your files from `Week02/hw` to `Week02`.

**Review by canbula — CHANGES_REQUESTED** [review]
If you can't figure out how to move your files, close this commit, and start from scratch.

**Comment by myr2001** [comment]
I have moved the files on my local machine and committed to github however when i check the website it does not show up. Do i close the commit?

**Pull request closed without merging**
