### PR TITLE
Create decorators_bora_ozisik.py

### PR DESCRIPTION
**Pull request by boraozisik**
## Checklist
- [ ] I have read the [CONTRIBUTING]
- [ ] I have performed a self-review of my own code
- [ ] I have run the code locally and it works as expected
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by canbula — CHANGES_REQUESTED** [review]
We need to find the memory usage while the given function is running, but not just by the parameters. Therefore, you need to follow a different approach.

**Comment by boraozisik** [comment]
I followed a different approach to measure memory usage, its done but I suppose the fail caused by another reason. The  error message says " 'function' object has no attribute 'counter' " but I create an 'counter' attribute for _performance function.

**Review by canbula — CHANGES_REQUESTED** [review]
The attributes must belong to the decorator function (`performance`) but not the inner one (`_performance`).

**Review by canbula — APPROVED** [review]
💯

**Pull request merged**
