### PR TITLE
homework.md

### PR DESCRIPTION
**Pull request by Erengokce03**
## Checklist
- [ ] I have read the [CONTRIBUTING]
- [ ] I have performed a self-review of my own code
- [ ] I have run the code locally and it works as expected
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by canbula — CHANGES_REQUESTED** [review]
Are you sure this one is a valid strategy? Do you have any citation?

**Comment by Erengokce03** [comment]
> Are you sure this one is a valid strategy? Do you have any citation?

I don't remember where I saw this method and I can not find it right now. But it is basically uses a diffirent kind of philosophers called Selfish_Philosopers. This type tries to claim both forks if they fail a decided number of time they put down the forks so other philosophers can use them. It was simple and I proposed to the team. We liked the idea and wrote the code for it.

**Comment by canbula** [comment]
It doesn't seem a selfish behavior to me.

**Comment by Erengokce03** [comment]
> It doesn't seem a selfish behavior to me.

I can provide code for the the selfish_philosopher class if that's okay.

**Comment by Erengokce03** [comment]
resim_2023-12-24_171902910

**Comment by canbula** [comment]
You should solve the deadlock situation as it occurs in the following code:
https://github.com/canbula/ParallelProgramming/blob/master/Week11/diningphilosophers.py

By the way your solution is based on the timeout solution and this strategy is already used by 4 groups.

**Comment by Erengokce03** [comment]
Okay. Then I am closing the request. Thanks for your time.

**Pull request closed without merging**
